import { Bell, ChevronDown, Command, LogOut, Search, User, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { getDashboardPath, getSession, logout } from "../../utilidades/autenticacion";

const MODULOS=[{nombre:"Dashboard",ruta:"/dashboard-admin"},{nombre:"Inventario",ruta:"/inventario"},{nombre:"Producción",ruta:"/produccion"},{nombre:"Trazabilidad",ruta:"/trazabilidad"},{nombre:"Ambiental",ruta:"/ambiental"},{nombre:"Calidad",ruta:"/calidad"},{nombre:"Costos",ruta:"/costos"},{nombre:"Personal",ruta:"/personal"},{nombre:"Inteligencia",ruta:"/ia"},{nombre:"Reportes",ruta:"/reportes"},{nombre:"Configuración",ruta:"/configuracion"}];
const roleLabel={admin:"Administrador",supervisor:"Supervisor",operario:"Operario"};
const leer=(tipo,fallback=[])=>{try{const value=localStorage.getItem(`aiden-${tipo}`);return value?JSON.parse(value):fallback}catch{return fallback}};

export default function BarraSuperior(){
 const navigate=useNavigate(); const session=getSession(); const [showProfile,setShowProfile]=useState(false); const [showNotifs,setShowNotifs]=useState(false); const [showPalette,setShowPalette]=useState(false); const [search,setSearch]=useState(""); const [notificaciones,setNotificaciones]=useState([]);
 const refrescar=()=>{const inventario=leer("inventario"),produccion=leer("produccion"),ambiental=leer("ambiental"),calidad=leer("calidad");const next=[];inventario.filter(r=>Number(r.stock)<=Number(r.minimo)).forEach(r=>next.push({id:`inv-${r.id}`,text:`Stock bajo: ${r.nombre}`,ruta:"/inventario",read:false}));produccion.filter(r=>r.etapa==="Cosecha").forEach(r=>next.push({id:`lot-${r.id}`,text:`${r.lote} listo para cosecha`,ruta:"/produccion",read:false}));ambiental.filter(r=>Number(r.temperatura)>27||Number(r.humedad)<55).forEach(r=>next.push({id:`amb-${r.id}`,text:`Condición ambiental fuera de rango: ${r.zona}`,ruta:"/ambiental",read:false}));calidad.filter(r=>r.estadoManual!=="Cerrada"&&r.prioridad==="Alta").forEach(r=>next.push({id:`cal-${r.id}`,text:`Incidencia alta en ${r.lote||r.codigo}`,ruta:"/calidad",read:false}));setNotificaciones(next.slice(0,8))};
 useEffect(()=>{refrescar();window.addEventListener("aiden-data-change",refrescar);return()=>window.removeEventListener("aiden-data-change",refrescar)},[]);
 useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setShowPalette(v=>!v);setSearch("")}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 const resultados=useMemo(()=>{const value=search.trim().toLowerCase();if(!value)return MODULOS;return MODULOS.filter(item=>item.nombre.toLowerCase().includes(value))},[search]);
 const irAModulo=ruta=>{navigate(ruta==="/dashboard-admin"?getDashboardPath(session?.role):ruta);setSearch("");setShowPalette(false);setShowNotifs(false)}; const noLeidas=notificaciones.filter(n=>!n.read).length;
 const marcarLeida=id=>{const item=notificaciones.find(n=>n.id===id);setNotificaciones(xs=>xs.map(n=>n.id===id?{...n,read:true}:n));if(item?.ruta)navigate(item.ruta)}; const marcarTodas=()=>setNotificaciones(xs=>xs.map(n=>({...n,read:true})));
 const handleLogout=()=>{logout();navigate("/login",{replace:true})}; const nombre=session?.name||"Usuario"; const rol=roleLabel[session?.role]||"Usuario";
 return <header className="relative z-20 flex h-16 shrink-0 items-center justify-between border-b border-[#E5EDE8] bg-white px-6"><section className="relative"><form onSubmit={e=>{e.preventDefault();if(resultados[0])irAModulo(resultados[0].ruta)}} className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} onFocus={()=>setShowPalette(true)} className="w-72 rounded-xl border border-slate-200 bg-slate-50 py-2 pl-9 pr-16 text-sm outline-none focus:border-emerald-500" placeholder="Buscar o ir a un módulo..." aria-label="Buscar módulos"/><kbd className="absolute right-2 top-1/2 hidden -translate-y-1/2 items-center gap-1 rounded-md border border-slate-200 bg-white px-1.5 py-0.5 text-[10px] font-semibold text-slate-400 sm:flex"><Command size={10}/>K</kbd></form>{showPalette&&<section className="absolute left-0 top-12 w-80 rounded-2xl border border-slate-200 bg-white p-2 shadow-xl"><header className="flex items-center justify-between px-2 pb-2"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Ir a</span><button type="button" onClick={()=>{setShowPalette(false);setSearch("")}} className="rounded-md p-1 text-slate-400 hover:bg-slate-100" aria-label="Cerrar búsqueda"><X size={13}/></button></header>{resultados.slice(0,7).map(item=><button key={item.ruta} type="button" onClick={()=>irAModulo(item.ruta)} className="flex w-full items-center justify-between rounded-xl px-3 py-2.5 text-left text-sm text-slate-700 hover:bg-emerald-50 hover:text-emerald-700"><span>{item.nombre}</span><span className="text-[10px] text-slate-400">Abrir</span></button>)}</section>}</section>
 <section className="flex items-center gap-3"><section className="relative"><button type="button" onClick={()=>{setShowNotifs(v=>!v);setShowProfile(false);setShowPalette(false)}} className="relative flex h-9 w-9 items-center justify-center rounded-xl hover:bg-slate-100" aria-label="Notificaciones"><Bell size={18} className="text-slate-500"/>{noLeidas>0&&<span className="absolute right-0.5 top-0.5 min-w-4 rounded-full bg-red-500 px-1 text-[9px] font-bold leading-4 text-white">{noLeidas}</span>}</button>{showNotifs&&<section className="absolute right-0 top-12 z-30 w-80 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl"><header className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Notificaciones</p>{noLeidas>0&&<button type="button" onClick={marcarTodas} className="text-[11px] font-semibold text-emerald-700">Marcar todas</button>}</header><ul className="max-h-96 divide-y divide-slate-100 overflow-y-auto">{notificaciones.length?notificaciones.map(n=><li key={n.id}><button type="button" onClick={()=>marcarLeida(n.id)} className={`w-full px-4 py-3 text-left hover:bg-slate-50 ${n.read?"opacity-50":""}`}><span className="flex gap-3"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${n.read?"bg-slate-300":"bg-emerald-500"}`}/><span className="text-sm leading-5 text-slate-700">{n.text}<span className="mt-1 block text-[11px] font-semibold text-emerald-700">Ver registro</span></span></span></button></li>):<li className="px-4 py-8 text-center text-sm text-slate-400">No hay alertas pendientes.</li>}</ul></section>}</section><section className="relative"><button type="button" onClick={()=>{setShowProfile(v=>!v);setShowNotifs(false)}} className="flex items-center gap-2 rounded-xl py-1.5 pl-2 pr-3 hover:bg-slate-100"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-600 text-white"><User size={14}/></span><section className="hidden text-left sm:block"><p className="text-sm font-medium leading-none text-slate-800">{nombre}</p><p className="mt-0.5 text-xs text-slate-400">{rol}</p></section><ChevronDown size={14} className="text-slate-400"/></button>{showProfile&&<section className="absolute right-0 top-12 z-30 w-56 rounded-2xl border border-slate-200 bg-white py-2 shadow-xl"><section className="border-b border-slate-100 px-4 py-3"><p className="text-sm font-medium text-slate-800">{nombre}</p><p className="mt-1 text-xs text-slate-400">{session?.email}</p></section><button type="button" onClick={handleLogout} className="flex w-full items-center gap-2 px-4 py-2.5 text-sm font-medium text-red-600 hover:bg-red-50"><LogOut size={14}/>Cerrar sesión</button></section>}</section></section></header>
}
