import { useMemo, useState } from "react";
import { AlertTriangle, Clock3, Droplets, History, Plus, Thermometer, X } from "lucide-react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const KEY="aiden-ambiental";
const seed=[
 {id:"AMB-001",zona:"Invernadero 1",temperatura:23.9,humedad:65,iluminacion:8400,fecha:"2026-09-14T09:30"},
 {id:"AMB-002",zona:"Invernadero 2",temperatura:28.6,humedad:71,iluminacion:7900,fecha:"2026-09-14T09:25"},
 {id:"AMB-003",zona:"Área de germinación",temperatura:22.4,humedad:69,iluminacion:6100,fecha:"2026-09-14T09:20"},
];
const read=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const uid=()=>`AMB-${Date.now().toString(36).toUpperCase()}`;
function Modal({onClose,children}){return <section className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4 backdrop-blur-sm"><article className="w-full max-w-lg rounded-2xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">Nueva lectura</h2><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={16}/></button></header><section className="p-5">{children}</section></article></section>}
function Input({label,...props}){return <label className="block text-sm font-medium text-slate-600">{label}<input {...props} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-emerald-500"/></label>}
function Kpi({label,value,detail,icon:Icon,tone="green"}){const t={green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",red:"bg-red-50 text-red-700"};return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${t[tone]}`}><Icon size={17}/></span><p className="mt-4 text-2xl font-bold text-slate-950">{value}</p><p className="text-xs font-semibold text-slate-600">{label}</p><p className="mt-1 text-[11px] text-slate-400">{detail}</p></article>}

export default function AmbientalOperativo(){
 const [rows,setRows]=useState(()=>read(KEY,seed));const [modal,setModal]=useState(false);const [zone,setZone]=useState("Todas");
 const save=data=>{setRows(data);write(KEY,data);window.dispatchEvent(new Event("aiden-data-change"));};
 const zones=[...new Set(rows.map(r=>r.zona))]; const latest=zones.map(z=>rows.filter(r=>r.zona===z).sort((a,b)=>new Date(b.fecha)-new Date(a.fecha))[0]); const alerts=latest.filter(r=>Number(r.temperatura)>27||Number(r.temperatura)<18||Number(r.humedad)<55||Number(r.humedad)>80); const filtered=zone==="Todas"?latest:latest.filter(r=>r.zona===zone);
 const add=f=>{save([{...f,id:uid(),temperatura:Number(f.temperatura),humedad:Number(f.humedad),iluminacion:Number(f.iluminacion)},...rows]);setModal(false)};
 return <section className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><section><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-emerald-700">AiDEN / seguimiento</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Ambiental</h1><p className="mt-1 text-sm text-slate-500">Monitorea condiciones por zona, detecta desviaciones y conserva el histórico para tomar decisiones.</p></section><button type="button" onClick={()=>setModal(true)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800"><Plus size={16}/>Registrar lectura</button></header>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Zonas" value={zones.length} detail="Con lecturas registradas" icon={Thermometer}/><Kpi label="En alerta" value={alerts.length} detail="Temperatura o humedad" icon={AlertTriangle} tone={alerts.length?"red":"green"}/><Kpi label="Lecturas" value={rows.length} detail="Histórico guardado" icon={History}/><Kpi label="Actualizado" value={rows[0]?new Intl.DateTimeFormat("es-CO",{hour:"2-digit",minute:"2-digit"}).format(new Date(rows[0].fecha)):"—"} detail="Última lectura" icon={Clock3} tone="amber"/></section>
 <section className="flex gap-1 overflow-x-auto">{["Todas",...zones].map(z=><button key={z} type="button" onClick={()=>setZone(z)} className={`whitespace-nowrap rounded-lg px-3 py-1.5 text-xs font-semibold ${zone===z?"bg-emerald-700 text-white":"bg-slate-100 text-slate-500"}`}>{z}</button>)}</section>
 {alerts.length>0&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><header className="flex items-center gap-2"><AlertTriangle size={16} className="text-amber-700"/><h2 className="font-semibold text-amber-900">Atención ambiental</h2></header><p className="mt-1 text-xs text-amber-800">Revisa las zonas marcadas antes de que una desviación se convierta en una incidencia de calidad.</p></section>}
 <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(r=>{const alert=Number(r.temperatura)>27||Number(r.temperatura)<18||Number(r.humedad)<55||Number(r.humedad)>80;const history=rows.filter(x=>x.zona===r.zona).slice(0,10).reverse();return <article key={r.zona} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><header className="flex items-start justify-between"><section><p className="text-[11px] uppercase tracking-wider text-slate-400">Zona</p><h2 className="mt-1 font-semibold text-slate-900">{r.zona}</h2></section><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${alert?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{alert?"Atención":"Estable"}</span></header><section className="mt-5 grid grid-cols-3 gap-2"><Metric label="Temperatura" value={`${r.temperatura} °C`} danger={Number(r.temperatura)>27||Number(r.temperatura)<18}/><Metric label="Humedad" value={`${r.humedad}%`} danger={Number(r.humedad)<55||Number(r.humedad)>80}/><Metric label="Luz" value={`${Number(r.iluminacion).toLocaleString("es-CO")} lux`}/></section><section className="mt-5 h-20"><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><XAxis dataKey="fecha" hide/><YAxis hide/><Tooltip labelFormatter={v=>new Date(v).toLocaleString("es-CO")} /><Line dataKey="temperatura" stroke="#176b45" strokeWidth={2} dot={false}/><Line dataKey="humedad" stroke="#6b8fb3" strokeWidth={1.5} dot={false}/></LineChart></ResponsiveContainer></section><footer className="mt-3 border-t border-slate-100 pt-3 text-[11px] text-slate-400">Última lectura: {new Date(r.fecha).toLocaleString("es-CO")}</footer></article>})}</section>
 {modal&&<Modal onClose={()=>setModal(false)}><form className="space-y-4" onSubmit={e=>{e.preventDefault();add(Object.fromEntries(new FormData(e.currentTarget).entries()))}}><Input name="zona" label="Zona" required placeholder="Invernadero 1"/><section className="grid grid-cols-3 gap-2"><Input name="temperatura" label="Temperatura °C" type="number" step="0.1" required/><Input name="humedad" label="Humedad %" type="number" required/><Input name="iluminacion" label="Iluminación lux" type="number" required/></section><Input name="fecha" label="Fecha y hora" type="datetime-local" defaultValue={new Date().toISOString().slice(0,16)}/><button className="w-full rounded-xl bg-emerald-700 py-2.5 text-sm font-semibold text-white">Guardar lectura</button></form></Modal>}
 </section>;
}
function Metric({label,value,danger=false}){return <section className={`rounded-xl p-3 ${danger?"bg-red-50":"bg-slate-50"}`}><p className="text-[10px] text-slate-400">{label}</p><p className={`mt-1 text-sm font-bold ${danger?"text-red-700":"text-slate-800"}`}>{value}</p></section>}
