import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, CircleAlert, Plus, Search, X } from "lucide-react";
import { getSession } from "../../utilidades/autenticacion";

const KEY="aiden-calidad"; const PEOPLE="aiden-personal"; const LOTS="aiden-produccion"; const TRACE="aiden-trazabilidad";
const seed=[
 {id:"INC-031",codigo:"INC-031",lote:"LT-2024-089",prioridad:"Alta",descripcion:"Hojas amarillas",responsable:"Laura M.",estado:"Abierta",accion:"",fecha:"2026-09-13"},
 {id:"INC-028",codigo:"INC-028",lote:"LT-2024-097",prioridad:"Media",descripcion:"Crecimiento irregular",responsable:"Andrés R.",estado:"En revisión",accion:"Revisar riego y sustrato",fecha:"2026-09-12"},
 {id:"INC-026",codigo:"INC-026",lote:"LT-2024-091",prioridad:"Baja",descripcion:"Bandejas deterioradas",responsable:"Camila P.",estado:"Cerrada",accion:"Reemplazar bandeja",fecha:"2026-09-10"},
];
const read=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value)); const uid=()=>`INC-${Date.now().toString(36).toUpperCase()}`;
function Modal({title,onClose,children}){return <section className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4 backdrop-blur-sm"><article className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">{title}</h2><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Cerrar"><X size={16}/></button></header><section className="p-5">{children}</section></article></section>}
function Input({label,...props}){return <label className="block text-sm font-medium text-slate-600">{label}<input {...props} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-emerald-500"/></label>}
function Select({label,children,...props}){return <label className="block text-sm font-medium text-slate-600">{label}<select {...props} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-emerald-500">{children}</select></label>}
function Textarea({label,...props}){return <label className="block text-sm font-medium text-slate-600">{label}<textarea {...props} className="mt-1 min-h-24 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-800 outline-none focus:border-emerald-500"/></label>}
function Kpi({label,value,detail,icon:Icon,tone="green"}){const t={green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",red:"bg-red-50 text-red-700"};return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${t[tone]}`}><Icon size={17}/></span><p className="mt-4 text-2xl font-bold text-slate-950">{value}</p><p className="text-xs font-semibold text-slate-600">{label}</p><p className="mt-1 text-[11px] text-slate-400">{detail}</p></article>}

export default function CalidadOperativo(){
 const session=getSession(); const role=session?.role||"operario"; const canResolve=role!=="operario";
 const [rows,setRows]=useState(()=>read(KEY,seed)); const [query,setQuery]=useState(""); const [filter,setFilter]=useState("Todas"); const [modal,setModal]=useState(false); const [selected,setSelected]=useState(null);
 const people=read(PEOPLE,[]); const lots=read(LOTS,[]); const open=rows.filter(r=>(r.estado??r.estadoManual)!=="Cerrada"); const high=open.filter(r=>r.prioridad==="Alta");
 const filtered=useMemo(()=>rows.filter(r=>(filter==="Todas"||(r.estado??r.estadoManual)===filter)&&`${r.codigo} ${r.lote} ${r.descripcion} ${r.responsable}`.toLowerCase().includes(query.toLowerCase())),[rows,filter,query]);
 const save=data=>{setRows(data);write(KEY,data);window.dispatchEvent(new Event("aiden-data-change"));};
 const create=f=>{const codigo=uid(); const nuevo={...f,id:codigo,codigo,estado:"Abierta",fecha:new Date().toISOString().slice(0,10)};save([nuevo,...rows]);setModal(false)};
 const update=(row,field,value)=>{if(!canResolve)return; const next=rows.map(r=>r.id===row.id?{...r,[field]:value}:r);save(next); if(field==="estado"&&value==="Cerrada"){const trace=read(TRACE,[]);write(TRACE,[{id:`TRZ-${Date.now()}`,lote:row.lote,evento:"Cierre de calidad",fecha:new Date().toISOString().slice(0,10),responsable:session?.name||row.responsable,detalle:`Se cerró ${row.codigo}: ${row.accion||"sin acción documentada"}.`},...trace]);}};
 return <section className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><section><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-emerald-700">AiDEN / seguimiento</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Calidad</h1><p className="mt-1 text-sm text-slate-500">Registra una desviación, deja claro quién la atiende y conserva su resolución.</p></section><button type="button" onClick={()=>setModal(true)} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800"><Plus size={16}/>Nueva incidencia</button></header>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Incidencias" value={rows.length} detail="Histórico" icon={ClipboardCheck}/><Kpi label="Abiertas" value={open.length} detail="En seguimiento" icon={CircleAlert} tone="amber"/><Kpi label="Alta prioridad" value={high.length} detail="Requieren respuesta" icon={AlertTriangle} tone="red"/><Kpi label="Resueltas" value={rows.filter(r=>(r.estado??r.estadoManual)==="Cerrada").length} detail="Cerradas" icon={CheckCircle2}/></section>
 <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-center gap-3 border-b border-slate-100 p-4"><section className="relative min-w-56 flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar incidencia, lote o responsable..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-3 text-sm outline-none"/></section>{["Todas","Abierta","En revisión","Cerrada"].map(s=><button key={s} type="button" onClick={()=>setFilter(s)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${filter===s?"bg-emerald-700 text-white":"bg-slate-100 text-slate-500"}`}>{s}</button>)}</header><section className="grid gap-3 p-4">{filtered.map(r=>{const estado=r.estado??r.estadoManual;return <article key={r.id} className="rounded-2xl border border-slate-200 p-4"><header className="flex flex-wrap items-start justify-between gap-3"><section><p className="font-mono text-[10px] text-emerald-700">{r.codigo} · {r.lote}</p><h2 className="mt-1 text-sm font-semibold text-slate-900">{r.descripcion}</h2><p className="mt-1 text-xs text-slate-400">{r.responsable} · {r.fecha}</p></section><section className="flex gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${r.prioridad==="Alta"?"bg-red-50 text-red-700":r.prioridad==="Media"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-500"}`}>{r.prioridad}</span>{canResolve?<select value={estado} onChange={e=>update(r,"estado",e.target.value)} className="rounded-lg border border-slate-200 px-2 py-1 text-[10px] font-semibold"><option>Abierta</option><option>En revisión</option><option>Cerrada</option></select>:<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold text-slate-500">{estado}</span>}</section></header><section className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]">{canResolve?<Input label="Acción correctiva" value={r.accion||""} onChange={e=>update(r,"accion",e.target.value)} placeholder="Qué se hará para corregir..."/>:<section className="rounded-xl bg-slate-50 p-3 text-sm"><p className="text-[10px] uppercase tracking-wider text-slate-400">Acción definida</p><p className="mt-1 text-sm text-slate-700">{r.accion||"Pendiente de definir por supervisión."}</p></section>}<button type="button" onClick={()=>setSelected(r)} className="self-end rounded-xl bg-slate-950 px-3 py-2.5 text-xs font-semibold text-white">Ver detalle</button></section></article>})}{filtered.length===0&&<p className="p-8 text-center text-sm text-slate-400">No hay incidencias que coincidan con el filtro.</p>}</section></section>
 {selected&&<Modal title={selected.codigo} onClose={()=>setSelected(null)}><section className="space-y-4"><div><p className="text-xl font-bold text-slate-900">{selected.descripcion}</p><p className="mt-1 text-sm text-slate-500">Lote {selected.lote} · responsable {selected.responsable}</p></div><div className="grid grid-cols-2 gap-3"><Kpi label="Prioridad" value={selected.prioridad} icon={AlertTriangle} tone={selected.prioridad==="Alta"?"red":"amber"}/><Kpi label="Estado" value={selected.estado??selected.estadoManual} icon={ClipboardCheck}/></div><section className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Acción correctiva</p><p className="mt-2 text-sm leading-6 text-slate-700">{selected.accion||"Todavía no documentada."}</p></section></section></Modal>}
 {modal&&<Modal title="Nueva incidencia" onClose={()=>setModal(false)}><QualityForm people={people} lots={lots} onSubmit={create}/></Modal>}
 </section>;
}
function QualityForm({people,lots,onSubmit}){const [f,setF]=useState({lote:lots[0]?.lote||"",prioridad:"Media",descripcion:"",responsable:people[0]?.nombre||""});return <form className="space-y-4" onSubmit={e=>{e.preventDefault();onSubmit(f)}}><Select label="Lote" value={f.lote} onChange={e=>setF({...f,lote:e.target.value})}>{lots.map(l=><option key={l.id}>{l.lote}</option>)}</Select><section className="grid grid-cols-2 gap-3"><Select label="Prioridad" value={f.prioridad} onChange={e=>setF({...f,prioridad:e.target.value})}><option>Baja</option><option>Media</option><option>Alta</option></Select><Select label="Responsable" value={f.responsable} onChange={e=>setF({...f,responsable:e.target.value})}>{people.map(p=><option key={p.id}>{p.nombre}</option>)}</Select></section><Textarea label="Qué se detectó" value={f.descripcion} onChange={e=>setF({...f,descripcion:e.target.value})} required/><button className="w-full rounded-xl bg-emerald-700 py-2.5 text-sm font-semibold text-white">Registrar incidencia</button></form>}
